# Generated by Django 5.2.15 on 2026-06-15 04:30

import envios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0005_alter_encomienda_required_relations_and_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomienda',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, unique=True, validators=[envios.validators.validar_codigo_encomienda]),
        ),
    ]
